# 测试环境配置
spring:
  # JPA 测试配置
  jpa:
    hibernate:
      # 使用 create-drop 会在测试结束时自动清理
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

sa-token:
  token-style: uuid
  timeout: 2592000   # 30 天
  active-timeout: -1

# 关闭 actuator 以减少测试加载失败风险
management:
  endpoints:
    web:
      exposure:
        include: "health"